
package helloworld.sample.ibm.com;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import helloworld.sample.ibm.helloworldimport.HelloResponseType;
import helloworld.sample.ibm.helloworldimport.HelloType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8-b131 
 * Generated source version: 2.1
 * 
 */
@WebService(name = "HelloWorld", targetNamespace = "urn:helloWorld/sample/ibm/com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorld {


    /**
     * 
     * @param hello
     * @return
     *     returns helloworld.sample.ibm.helloworldimport.HelloResponseType
     */
    @WebMethod(action = "urn:helloWorld/sample/ibm/com/hello")
    @WebResult(name = "helloResponse", targetNamespace = "urn:helloWorld/sample/ibm/com", partName = "helloResult")
    public HelloResponseType hello(
        @WebParam(name = "hello", targetNamespace = "urn:helloWorld/sample/ibm/com", partName = "hello")
        HelloType hello);

}
