
package helloworld.sample.ibm.com;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "HelloWorldService", targetNamespace = "urn:helloWorld/sample/ibm/com", wsdlLocation = "FILL_IN_BY_SERVER")
public class HelloWorldService
    extends Service
{

    private final static URL HELLOWORLDSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOWORLDSERVICE_EXCEPTION;
    private final static QName HELLOWORLDSERVICE_QNAME = new QName("urn:helloWorld/sample/ibm/com", "HelloWorldService");

    static {
        HELLOWORLDSERVICE_WSDL_LOCATION = helloworld.sample.ibm.com.HelloWorldService.class.getResource("FILL_IN_BY_SERVER");
        WebServiceException e = null;
        if (HELLOWORLDSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'FILL_IN_BY_SERVER' wsdl. Place the resource correctly in the classpath.");
        }
        HELLOWORLDSERVICE_EXCEPTION = e;
    }

    public HelloWorldService() {
        super(__getWsdlLocation(), HELLOWORLDSERVICE_QNAME);
    }

    public HelloWorldService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns HelloWorld
     */
    @WebEndpoint(name = "port")
    public HelloWorld getPort() {
        return super.getPort(new QName("urn:helloWorld/sample/ibm/com", "port"), HelloWorld.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorld
     */
    @WebEndpoint(name = "port")
    public HelloWorld getPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:helloWorld/sample/ibm/com", "port"), HelloWorld.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOWORLDSERVICE_EXCEPTION!= null) {
            throw HELLOWORLDSERVICE_EXCEPTION;
        }
        return HELLOWORLDSERVICE_WSDL_LOCATION;
    }

}
